export const ALL_EVENT_REQUEST = "ALL_EVENT_REQUEST";
export const ALL_EVENT_SUCCESS = "ALL_EVENT_SUCCESS";
export const ALL_EVENT_FAIL = "ALL_EVENT_FAIL";

export const MY_EVENT_REQUEST = "MY_EVENT_REQUEST";
export const MY_EVENT_SUCCESS = "MY_EVENT_SUCCESS";
export const MY_EVENT_FAIL = "MY_EVENT_FAIL";

export const NEW_EVENT_REQUEST = "NEW_EVENT_REQUEST";
export const NEW_EVENT_SUCCESS = "NEW_EVENT_SUCCESS";
export const NEW_EVENT_RESET = "NEW_EVENT_RESET";
export const NEW_EVENT_FAIL = "NEW_EVENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
